# These are supported funding model platforms

github: [<img>]
patreon: <img>
open_collective: <img>
ko_fi: <img>
tidelift: <img>
community_bridge: <img>
liberapay: <img>
issuehunt: <img>
otechie: <img>
lfx_crowdfunding: <img>
custom: ['javascript:alert(1)','https://google.ca']
